---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[logstash-forwarder::default]
    attributes:
      logstash-forwarder:
        ssl_data_bag_name: 'server'
